services:
  mongo:
    image: mongo:7
    container_name: bikes2beans-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: bikes2beans

volumes:
  mongo_data:
